// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_daily_challenge_monster = "CgkInbOFtb4REAIQDA"; // <GPGSID>
        public const string achievement_love_the_world = "CgkInbOFtb4REAIQEQ"; // <GPGSID>
        public const string achievement_daily_challenge_1 = "CgkInbOFtb4REAIQAw"; // <GPGSID>
        public const string achievement_daily_challenge_2 = "CgkInbOFtb4REAIQBA"; // <GPGSID>
        public const string achievement_with_us = "CgkInbOFtb4REAIQAQ"; // <GPGSID>
        public const string achievement_bananananana = "CgkInbOFtb4REAIQEA"; // <GPGSID>
        public const string achievement_daily_challenge_master = "CgkInbOFtb4REAIQCw"; // <GPGSID>
        public const string achievement_this_is_a = "CgkInbOFtb4REAIQFA"; // <GPGSID>
        public const string leaderboard_dailytime = "CgkInbOFtb4REAIQBg"; // <GPGSID>
        public const string achievement_hipacman = "CgkInbOFtb4REAIQDw"; // <GPGSID>
        public const string achievement_daily_challenge_badass = "CgkInbOFtb4REAIQDQ"; // <GPGSID>
        public const string achievement_do_re_mi = "CgkInbOFtb4REAIQEw"; // <GPGSID>
        public const string leaderboard_totaltime = "CgkInbOFtb4REAIQBw"; // <GPGSID>
        public const string achievement_fly_in_the_sky = "CgkInbOFtb4REAIQFQ"; // <GPGSID>
        public const string achievement_find_turtle = "CgkInbOFtb4REAIQEg"; // <GPGSID>
        public const string achievement_with_us_2 = "CgkInbOFtb4REAIQAg"; // <GPGSID>
        public const string achievement_love__love = "CgkInbOFtb4REAIQDg"; // <GPGSID>
        public const string achievement_login_game_1 = "CgkInbOFtb4REAIQCA"; // <GPGSID>
        public const string achievement_login_game_2 = "CgkInbOFtb4REAIQCQ"; // <GPGSID>
        public const string achievement_login_game_3 = "CgkInbOFtb4REAIQCg"; // <GPGSID>

}

